// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emukdacjjybtsxbltchw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtdWtkYWNqanlidHN4Ymx0Y2h3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg5NDk1ODEsImV4cCI6MjA4NDUyNTU4MX0.cxzPfm0t4QldmxYv1omfn9QO2TIsyxwa__Q4X8EzXQk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});